# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import interface.ai_service_pb2 as ai__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AutoGeneratedPosts = channel.unary_unary(
                '/ai_processor.AiService/AutoGeneratedPosts',
                request_serializer=ai__service__pb2.AutoGeneratedRequest.SerializeToString,
                response_deserializer=ai__service__pb2.AutoGeneratedResponse.FromString,
                _registered_method=True)
        self.ManualGeneratedPosts = channel.unary_unary(
                '/ai_processor.AiService/ManualGeneratedPosts',
                request_serializer=ai__service__pb2.ManualGeneratedRequest.SerializeToString,
                response_deserializer=ai__service__pb2.ManualGeneratedResponse.FromString,
                _registered_method=True)
        self.AnalyticPosts = channel.unary_unary(
                '/ai_processor.AiService/AnalyticPosts',
                request_serializer=ai__service__pb2.AnalyticPostsRequest.SerializeToString,
                response_deserializer=ai__service__pb2.AnalyticPostsResponse.FromString,
                _registered_method=True)


class AiServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AutoGeneratedPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ManualGeneratedPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyticPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AutoGeneratedPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.AutoGeneratedPosts,
                    request_deserializer=ai__service__pb2.AutoGeneratedRequest.FromString,
                    response_serializer=ai__service__pb2.AutoGeneratedResponse.SerializeToString,
            ),
            'ManualGeneratedPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.ManualGeneratedPosts,
                    request_deserializer=ai__service__pb2.ManualGeneratedRequest.FromString,
                    response_serializer=ai__service__pb2.ManualGeneratedResponse.SerializeToString,
            ),
            'AnalyticPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyticPosts,
                    request_deserializer=ai__service__pb2.AnalyticPostsRequest.FromString,
                    response_serializer=ai__service__pb2.AnalyticPostsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_processor.AiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_processor.AiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AutoGeneratedPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_processor.AiService/AutoGeneratedPosts',
            ai__service__pb2.AutoGeneratedRequest.SerializeToString,
            ai__service__pb2.AutoGeneratedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ManualGeneratedPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_processor.AiService/ManualGeneratedPosts',
            ai__service__pb2.ManualGeneratedRequest.SerializeToString,
            ai__service__pb2.ManualGeneratedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyticPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_processor.AiService/AnalyticPosts',
            ai__service__pb2.AnalyticPostsRequest.SerializeToString,
            ai__service__pb2.AnalyticPostsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
