# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analytic_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'analytic_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61nalytic_service.proto\x12\rai_generation\"6\n\x13ParsingPostsRequest\x12\x11\n\tmessenger\x18\x01 \x01(\t\x12\x0c\n\x04lang\x18\x02 \x01(\t\"4\n\x14ParsingPostsResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t\"7\n\x14\x41nalyticPostsRequest\x12\x11\n\tmessenger\x18\x01 \x01(\t\x12\x0c\n\x04lang\x18\x02 \x01(\t\"5\n\x15\x41nalyticPostsResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t2\xc6\x01\n\x0f\x41nalyticService\x12W\n\x0cParsingPosts\x12\".ai_generation.ParsingPostsRequest\x1a#.ai_generation.ParsingPostsResponse\x12Z\n\rAnalyticPosts\x12#.ai_generation.AnalyticPostsRequest\x1a$.ai_generation.AnalyticPostsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analytic_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARSINGPOSTSREQUEST']._serialized_start=41
  _globals['_PARSINGPOSTSREQUEST']._serialized_end=95
  _globals['_PARSINGPOSTSRESPONSE']._serialized_start=97
  _globals['_PARSINGPOSTSRESPONSE']._serialized_end=149
  _globals['_ANALYTICPOSTSREQUEST']._serialized_start=151
  _globals['_ANALYTICPOSTSREQUEST']._serialized_end=206
  _globals['_ANALYTICPOSTSRESPONSE']._serialized_start=208
  _globals['_ANALYTICPOSTSRESPONSE']._serialized_end=261
  _globals['_ANALYTICSERVICE']._serialized_start=264
  _globals['_ANALYTICSERVICE']._serialized_end=462
# @@protoc_insertion_point(module_scope)
