# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import interface.analytic_service_pb2 as analytic__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in analytic_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyticServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParsingPosts = channel.unary_unary(
                '/ai_generation.AnalyticService/ParsingPosts',
                request_serializer=analytic__service__pb2.ParsingPostsRequest.SerializeToString,
                response_deserializer=analytic__service__pb2.ParsingPostsResponse.FromString,
                _registered_method=True)
        self.AnalyticPosts = channel.unary_unary(
                '/ai_generation.AnalyticService/AnalyticPosts',
                request_serializer=analytic__service__pb2.AnalyticPostsRequest.SerializeToString,
                response_deserializer=analytic__service__pb2.AnalyticPostsResponse.FromString,
                _registered_method=True)


class AnalyticServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ParsingPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyticPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParsingPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.ParsingPosts,
                    request_deserializer=analytic__service__pb2.ParsingPostsRequest.FromString,
                    response_serializer=analytic__service__pb2.ParsingPostsResponse.SerializeToString,
            ),
            'AnalyticPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyticPosts,
                    request_deserializer=analytic__service__pb2.AnalyticPostsRequest.FromString,
                    response_serializer=analytic__service__pb2.AnalyticPostsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_generation.AnalyticService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_generation.AnalyticService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyticService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ParsingPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_generation.AnalyticService/ParsingPosts',
            analytic__service__pb2.ParsingPostsRequest.SerializeToString,
            analytic__service__pb2.ParsingPostsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyticPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_generation.AnalyticService/AnalyticPosts',
            analytic__service__pb2.AnalyticPostsRequest.SerializeToString,
            analytic__service__pb2.AnalyticPostsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
