# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telegram_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'telegram_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16telegram_service.proto\x12\tinterface\"a\n\x11GetContentRequest\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x15\n\rparsing_count\x18\x02 \x01(\r\x12\x16\n\tlast_post\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x0c\n\n_last_post\"_\n\x12GetContentResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\r\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t\x12$\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x16.interface.ContentData\"\xe6\x01\n\x0b\x43ontentData\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05views\x18\x02 \x01(\r\x12\x10\n\x08\x66orwards\x18\x03 \x01(\r\x12\x15\n\rreplies_count\x18\x04 \x01(\r\x12\x17\n\x0ftotal_reactions\x18\x05 \x01(\r\x12\r\n\x05stars\x18\x06 \x01(\r\x12\x11\n\tposted_at\x18\x07 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x08 \x01(\t\x12\x0b\n\x03url\x18\t \x03(\t\x12:\n\x13reactions_breakdown\x18\n \x03(\x0b\x32\x1d.interface.ReactionsBreakdown\"2\n\x12ReactionsBreakdown\x12\r\n\x05\x65moji\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\r\"I\n\x12PostContentRequest\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\timage_url\x18\x03 \x01(\t\":\n\x13PostContentResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\r\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t2\xb1\x01\n\x16TelegramControlService\x12I\n\nGetContent\x12\x1c.interface.GetContentRequest\x1a\x1d.interface.GetContentResponse\x12L\n\x0bPostContent\x12\x1d.interface.PostContentRequest\x1a\x1e.interface.PostContentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telegram_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCONTENTREQUEST']._serialized_start=37
  _globals['_GETCONTENTREQUEST']._serialized_end=134
  _globals['_GETCONTENTRESPONSE']._serialized_start=136
  _globals['_GETCONTENTRESPONSE']._serialized_end=231
  _globals['_CONTENTDATA']._serialized_start=234
  _globals['_CONTENTDATA']._serialized_end=464
  _globals['_REACTIONSBREAKDOWN']._serialized_start=466
  _globals['_REACTIONSBREAKDOWN']._serialized_end=516
  _globals['_POSTCONTENTREQUEST']._serialized_start=518
  _globals['_POSTCONTENTREQUEST']._serialized_end=591
  _globals['_POSTCONTENTRESPONSE']._serialized_start=593
  _globals['_POSTCONTENTRESPONSE']._serialized_end=651
  _globals['_TELEGRAMCONTROLSERVICE']._serialized_start=654
  _globals['_TELEGRAMCONTROLSERVICE']._serialized_end=831
# @@protoc_insertion_point(module_scope)
