create table "public"."payments" (
    "id" bigint generated by default as identity not null,
    "user_id" bigint not null,
    "status" character varying,
    "valid_until" date,
    "payed_at" date,
    "tariff_id" bigint,
    "amount" integer,
    "currency" character varying,
    "balance" integer,
    "created_at" timestamp with time zone not null default now()
);


create table "public"."tariffs" (
    "id" bigint generated by default as identity not null,
    "title" character varying,
    "description" text,
    "price" bigint,
    "currency" character varying,
    "valid_until" date,
    "created_at" timestamp with time zone not null default now()
);


CREATE UNIQUE INDEX payments_pkey ON public.payments USING btree (id, user_id);

CREATE UNIQUE INDEX tariffs_pkey ON public.tariffs USING btree (id);

alter table "public"."payments" add constraint "payments_pkey" PRIMARY KEY using index "payments_pkey";

alter table "public"."tariffs" add constraint "tariffs_pkey" PRIMARY KEY using index "tariffs_pkey";

grant delete on table "public"."payments" to "anon";

grant insert on table "public"."payments" to "anon";

grant references on table "public"."payments" to "anon";

grant select on table "public"."payments" to "anon";

grant trigger on table "public"."payments" to "anon";

grant truncate on table "public"."payments" to "anon";

grant update on table "public"."payments" to "anon";

grant delete on table "public"."payments" to "authenticated";

grant insert on table "public"."payments" to "authenticated";

grant references on table "public"."payments" to "authenticated";

grant select on table "public"."payments" to "authenticated";

grant trigger on table "public"."payments" to "authenticated";

grant truncate on table "public"."payments" to "authenticated";

grant update on table "public"."payments" to "authenticated";

grant delete on table "public"."payments" to "service_role";

grant insert on table "public"."payments" to "service_role";

grant references on table "public"."payments" to "service_role";

grant select on table "public"."payments" to "service_role";

grant trigger on table "public"."payments" to "service_role";

grant truncate on table "public"."payments" to "service_role";

grant update on table "public"."payments" to "service_role";

grant delete on table "public"."tariffs" to "anon";

grant insert on table "public"."tariffs" to "anon";

grant references on table "public"."tariffs" to "anon";

grant select on table "public"."tariffs" to "anon";

grant trigger on table "public"."tariffs" to "anon";

grant truncate on table "public"."tariffs" to "anon";

grant update on table "public"."tariffs" to "anon";

grant delete on table "public"."tariffs" to "authenticated";

grant insert on table "public"."tariffs" to "authenticated";

grant references on table "public"."tariffs" to "authenticated";

grant select on table "public"."tariffs" to "authenticated";

grant trigger on table "public"."tariffs" to "authenticated";

grant truncate on table "public"."tariffs" to "authenticated";

grant update on table "public"."tariffs" to "authenticated";

grant delete on table "public"."tariffs" to "service_role";

grant insert on table "public"."tariffs" to "service_role";

grant references on table "public"."tariffs" to "service_role";

grant select on table "public"."tariffs" to "service_role";

grant trigger on table "public"."tariffs" to "service_role";

grant truncate on table "public"."tariffs" to "service_role";

grant update on table "public"."tariffs" to "service_role";


