# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import interface.telegram_service_pb2 as telegram__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in telegram_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TelegramControlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetContent = channel.unary_unary(
                '/interface.TelegramControlService/GetContent',
                request_serializer=telegram__service__pb2.GetContentRequest.SerializeToString,
                response_deserializer=telegram__service__pb2.GetContentResponse.FromString,
                _registered_method=True)
        self.PostContent = channel.unary_unary(
                '/interface.TelegramControlService/PostContent',
                request_serializer=telegram__service__pb2.PostContentRequest.SerializeToString,
                response_deserializer=telegram__service__pb2.PostContentResponse.FromString,
                _registered_method=True)


class TelegramControlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelegramControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetContent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContent,
                    request_deserializer=telegram__service__pb2.GetContentRequest.FromString,
                    response_serializer=telegram__service__pb2.GetContentResponse.SerializeToString,
            ),
            'PostContent': grpc.unary_unary_rpc_method_handler(
                    servicer.PostContent,
                    request_deserializer=telegram__service__pb2.PostContentRequest.FromString,
                    response_serializer=telegram__service__pb2.PostContentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'interface.TelegramControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('interface.TelegramControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TelegramControlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interface.TelegramControlService/GetContent',
            telegram__service__pb2.GetContentRequest.SerializeToString,
            telegram__service__pb2.GetContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PostContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interface.TelegramControlService/PostContent',
            telegram__service__pb2.PostContentRequest.SerializeToString,
            telegram__service__pb2.PostContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
